language: elixir
cache:
  - apt
dist: trusty
elixir:
  - 1.4.2
  - 1.4.5
otp_release:
  - 19.3
  - 20.0
matrix:
  exclude:
    - elixir: 1.4.2
      otp_release: 20.0
env:
- MIX_ENV=test

branches:
  only:
    - master
    - develop
